name: Build and Push Docker Image

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Verify Java version
      - name: Verify Java
        run: java -version

      # 4. Start Oracle Database
      - name: Start Oracle Database
        run: |
          docker run -d \
            --name oracle-db \
            -p 1521:1521 \
            -e ORACLE_PASSWORD=NewPass123 \
            -e APP_USER=MYAPP \
            -e APP_USER_PASSWORD=NewPass123 \
            gvenzl/oracle-free:23-slim

      # 5. Wait for Oracle Database
      - name: Wait for Oracle Database
        run: |
          echo "Waiting for Oracle Database..."

          for i in {1..30}; do

            if docker exec oracle-db healthcheck.sh >/dev/null 2>&1; then
              echo "Oracle Database is ready!"
              exit 0
            fi

            echo "Oracle is not ready yet..."
            sleep 10

          done

          echo "Oracle Database failed to start"

          docker logs oracle-db

          exit 1

      # 6. Check Oracle Database
      - name: Check Oracle Database
        run: |
          docker ps
          docker logs oracle-db --tail 50

      # 7. Build, Test, JaCoCo and SonarCloud
      - name: Build and Analyze
        env:
          SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
          SPRING_DATASOURCE_USERNAME: MYAPP
          SPRING_DATASOURCE_PASSWORD: NewPass123
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.token=$SONAR_TOKEN